# hash:sha256:7b997f7495c72dd968b4de5dd1f8025b395d62a6c654080c23dc3d2d9b061278
FROM registry.codeocean.com/codeocean/miniconda3:4.9.2-python3.8-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip3 install -U --no-cache-dir \
    keras==2.7.0 \
    matplotlib==3.5.1 \
    networkx==2.6.3 \
    numpy==1.22.0 \
    pandas==1.3.5 \
    scipy==1.7.3 \
    tensorflow==2.7.0